name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.3'  # You can specify the Python version here

    - name: Install dependencies
      run: pip install -r requirements.txt  # Adjust this according to your project setup
      
    - name: Run tests
      run: python -m unittest discover
